-- Add essential columns for Excel import
ALTER TABLE users ADD COLUMN IF NOT EXISTS personnel_number VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS title VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS payroll_area VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS discom VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS personnel_area VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS employee_group VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS official_email VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS personal_mobile VARCHAR(15);
ALTER TABLE users ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(10);

-- Update existing columns
ALTER TABLE users ALTER COLUMN department TYPE VARCHAR(200);
ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(100);