-- Add new columns to users table based on Excel structure
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS personnel_number VARCHAR(50),
ADD COLUMN IF NOT EXISTS title VARCHAR(10),
ADD COLUMN IF NOT EXISTS previous_personnel_no VARCHAR(50),
ADD COLUMN IF NOT EXISTS old_audit_no VARCHAR(50),
ADD COLUMN IF NOT EXISTS payroll_area VARCHAR(100),
ADD COLUMN IF NOT EXISTS discom VARCHAR(50),
ADD COLUMN IF NOT EXISTS personnel_area VARCHAR(100),
ADD COLUMN IF NOT EXISTS personnel_sub_area VARCHAR(100),
ADD COLUMN IF NOT EXISTS district VARCHAR(100),
ADD COLUMN IF NOT EXISTS employee_group VARCHAR(50),
ADD COLUMN IF NOT EXISTS employee_sub_group VARCHAR(50),
ADD COLUMN IF NOT EXISTS reporting_officer_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS reporting_officer_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS department_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS ddo_office_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS ddo_office_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS ddo_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS position_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS position_text VARCHAR(100),
ADD COLUMN IF NOT EXISTS job_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS job_description VARCHAR(200),
ADD COLUMN IF NOT EXISTS cost_center VARCHAR(50),
ADD COLUMN IF NOT EXISTS cost_center_text VARCHAR(100),
ADD COLUMN IF NOT EXISTS work_schedule VARCHAR(50),
ADD COLUMN IF NOT EXISTS shift_details VARCHAR(100),
ADD COLUMN IF NOT EXISTS date_of_joining DATE,
ADD COLUMN IF NOT EXISTS designation_at_joining VARCHAR(100),
ADD COLUMN IF NOT EXISTS date_of_birth DATE,
ADD COLUMN IF NOT EXISTS age VARCHAR(20),
ADD COLUMN IF NOT EXISTS date_of_retirement DATE,
ADD COLUMN IF NOT EXISTS gender VARCHAR(10),
ADD COLUMN IF NOT EXISTS religion VARCHAR(50),
ADD COLUMN IF NOT EXISTS category VARCHAR(50),
ADD COLUMN IF NOT EXISTS sub_category VARCHAR(50),
ADD COLUMN IF NOT EXISTS marital_status VARCHAR(20),
ADD COLUMN IF NOT EXISTS personal_mobile VARCHAR(15),
ADD COLUMN IF NOT EXISTS official_mobile VARCHAR(15),
ADD COLUMN IF NOT EXISTS official_email VARCHAR(100),
ADD COLUMN IF NOT EXISTS personal_email VARCHAR(100),
ADD COLUMN IF NOT EXISTS pf_account_no VARCHAR(50),
ADD COLUMN IF NOT EXISTS pension_account_no VARCHAR(50),
ADD COLUMN IF NOT EXISTS fathers_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS mother_name VARCHAR(100);

-- Update existing columns to allow longer values
ALTER TABLE users 
ALTER COLUMN department TYPE VARCHAR(200),
ALTER COLUMN email TYPE VARCHAR(100);

-- Create index on personnel_number for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_personnel_number ON users(personnel_number);